name: flutter_slide
description: "Flutter slide source module"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  xml: ^6.5.0
  path_drawing: ^1.0.1
  flutter_svg: ^2.1.0
  text_to_path_maker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Hefty Reward Single Line
      fonts:
        - asset: lib/assets/fonts/HeftyRewardSingleLine-JRqWx.ttf
  assets:
    - assets/images/
  module:
    androidX: true
    androidPackage: com.example.flutter_slide
    iosBundleIdentifier: com.example.flutterSlide

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    outputs:
      class_name: ModuleAssets
      package_parameter_enabled: true
