name: flutter_kaigi_slide
description: "FlutterKaigi slide source module"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  xml: ^6.5.0
  path_drawing: ^1.0.1
  text_to_path_maker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Hefty Reward Single Line
      fonts:
        - asset: lib/assets/fonts/HeftyRewardSingleLine-JRqWx.ttf

  module:
    androidX: true
    androidPackage: com.example.flutter_kaigi_slide
    iosBundleIdentifier: com.example.flutterKaigiSlide
