name: flutter_kaigi_slide
description: "FlutterKaigi slide source module"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_kaigi_slide
    iosBundleIdentifier: com.example.flutterKaigiSlide
