name: flutter_kaigi_slide_example
description: "FlutterKaigi slide source example"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_kaigi_slide:
    path: ../
  flutter_svg: ^2.1.0
  dev: ^1.0.0
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
