# グローバルプラットフォーム設定
platform :ios, '16.0'

# Flutterプロジェクトのパス
flutter_application_path = '../flutter_kaigi_slide'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

# メインのAppターゲット
target 'Slidys' do
  # このターゲットにはFlutterの依存を含めません
  use_frameworks!  # 必要に応じてコメントアウト可能
  install_all_flutter_pods(flutter_application_path)
end

# post_installブロックの設定
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = '*.pcm'
    end
  end
end
